### ISSUE TITLE
【課題】Homestead上で動かして表示する

### ISSUE THREAD

**Issue by ishiitakeru** [forthelocal/laravel_test01#1]
このレポジトリをローカルにクローンする。
Homesteadの設定とhostの設定を編集し、このLaravelをHomestead上で動作させてブラウザに表示させる。

## [参考]石井MACの設定

Homestead.yaml

``` 
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code/user_home_test
    - map: ~/Documents/workspace/yg/laravel_test01
      to: /home/vagrant/Code/laravel_test01

sites:
    - map: homestead.app
      to: /home/vagrant/Code/user_home_test/public
    - map: laravel_test01.app
      to: /home/vagrant/Code/laravel_test01/public

databases:
    - homestead
    - laravel_test01

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 50000
#       to: 5000
#     - send: 7777
#       to: 777
#       protocol: udp
```

.env

``` 
APP_ENV=local
APP_KEY=base64:nPkn/JHLWpynJQzIB8bGD9FrJzL96B6ni2Ntc/ZwFXw=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://laravel_test01.app

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravel_test01
DB_USERNAME=homestead
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_KEY=
PUSHER_SECRET=
```

/private/etc/hosts

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 

127.0.0.1 localhost.dev
127.0.0.1 preview.localhost.dev
192.168.10.10  homestead.app
192.168.10.10  laravel_test01.app
```
